---
- name: Icinga2 | Add Icinga2 repository apt-key
  apt_key:
    url: "{{ icinga2_apt_key_url }}"
    state: present

- name: Icinga2 | Add Icinga2 repository
  apt_repository:
    repo: "{{ icinga2_apt_repository }}"
    state: present

- name: Icinga2 | Install Icinga2
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items:
    - icinga2
    - nagios-plugins
