---
- name: Icinga2 Node | Set pki folder permissions
  file:
      dest: /etc/icinga2/pki
      owner: nagios
      group: nagios
      state: directory

- name: Icinga2 Node | Create new self signed certificate
  command: icinga2 pki new-cert --cn {{ ansible_fqdn }} \
          --key /etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.key \
          --cert /etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.crt \
          creates=/etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.key
  notify:
    - restart icinga2
    - icinga2 master update nodes

- name: Icinga2 Node | Trust the master
  command: icinga2 pki save-cert --key /etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.key \
          --cert /etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.crt \
          --trustedcert /etc/icinga2/pki/trusted-master.crt \
          --host {{ icinga2_master }} \
          creates=/etc/icinga2/pki/trusted-master.crt
  notify:
    - restart icinga2
    - icinga2 master update nodes

- name: Icinga2 Node | Generate ticket on master
  command: icinga2 pki ticket --cn {{ ansible_fqdn }}
  delegate_to: "{{ icinga2_master }}"
  register: icinga2_ticket
  notify:
    - restart icinga2
    - icinga2 master update nodes

- name: Icinga2 Node | Send the certificate to the master
  command: icinga2 pki request --host {{ icinga2_master }} \
          --port 5665 \
          --ticket {{ icinga2_ticket.stdout }} \
          --key /etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.key \
          --cert /etc/icinga2/pki/icinga2-{{ ansible_fqdn }}.crt \
          --trustedcert /etc/icinga2/pki/trusted-master.crt \
          --ca /etc/icinga2/pki/ca.crt \
          creates=/etc/icinga2/pki/ca.crt
  notify:
    - restart icinga2
    - icinga2 master update nodes

- name: Icinga2 Node | Configure zone and endpoint
  command: icinga2 node setup --ticket {{ icinga2_ticket.stdout }} \
            --endpoint {{ icinga2_master }},{{ icinga2_master }},5665 \
            --zone {{ ansible_fqdn }} \
            --cn {{ ansible_fqdn }} \
            --master_host {{ icinga2_master }} \
            --accept-config \
            --accept-commands \
            --trustedcert /etc/icinga2/pki/trusted-master.crt
  notify:
    - restart icinga2
    - icinga2 master update nodes
